#include <windows.h>
#include <Engine.h>
#include "Player.h"
#include "SnowMan.h"
#include "RessourcesManager.h"
#include "TileMap.h"
#include "MenuManager.h"

/*TODO
- Pathfinding A*
- state Machine for ennemies
- other enemies
- other weapons

*/
int APIENTRY WinMain(HINSTANCE hInst, HINSTANCE hInstPrev, PSTR cmdline, int cmdshow) 
{	
    //----------------------------------INIT WORLD----------------------------------
    gce::Console::Init();
    gce::GameManager::Create();
    RessourcesManager::Create();
    gce::Scene& scene = gce::Scene::Create();
	TileMap tileMap(100, 100, 10, .5f, scene, { -25.0f,0.0f,-25.0f });
    gce::WindowParam params;
    params.title = L"GCE Engine Window";
    params.width = 1920;
    params.height = 1080;
    params.isFullScreen = true;
    params.isSplitScreen = false;
    params.screenDisposition = gce::SplitScreenDisposition::SQUARE_4_PLAYERS;

    gce::GameObject& CameraObject = gce::GameObject::Create(scene);
    CameraObject.transform.LocalTranslate({ 0,0, -10 });
    gce::Camera* pCamera = CameraObject.AddComponent<gce::Camera>();
    pCamera->SetMainCamera();
    pCamera->SetType(gce::PERSPECTIVE);
    pCamera->perspective.fov = XM_PIDIV4;
    pCamera->perspective.nearPlane = 0.001f;
    pCamera->perspective.farPlane = 500.0f;
    pCamera->perspective.aspectRatio = 1000.0f / 800.0f;
    pCamera->perspective.up = { 0.0f, 1.0f, 0.0f };

    GameObject& PlayerObject = GameObject::Create(scene);
    Light* light = PlayerObject.AddComponent<Light>();
    light->DefaultDirectionLight();
    light->intensity = 1.0f;

    GameObject& SnowManObject = GameObject::Create(scene);

    GameObject& testObject = GameObject::Create(scene);
    MeshRenderer* pMeshRenderer = testObject.AddComponent<MeshRenderer>();
    pMeshRenderer->SetGeometry(SHAPES.CUBE);
    Texture* pNewTexture = new Texture("res/Exemple/TexturesTest.jpg");
    pMeshRenderer->SetAlbedoTexture(pNewTexture);
    testObject.AddComponent<BoxCollider>()->SetActive(true);
    testObject.AddComponent<PhysicComponent>();
    testObject.GetComponent<PhysicComponent>()->SetGravityScale(0.0f);
    testObject.SetName("TestObject");

   GameObject& Weapon = GameObject::Create(scene);
    Weapon.transform.SetWorldPosition({ .0f,.0f,.0f });
    MeshRenderer* pWeaponRenderer = Weapon.AddComponent<MeshRenderer>();
    pWeaponRenderer->SetGeometry(GeometryFactory::LoadGeometry("res/Exemple/bottle.obj"));
    Weapon.transform.LocalScale({ 0.03,0.03,0.03 });

    GameObject& Floor = GameObject::Create(scene);
    Floor.transform.SetWorldPosition({ -5.0f,-10.0f,-5.0f });
    MeshRenderer* pFloorRenderer = Floor.AddComponent<MeshRenderer>();
    pFloorRenderer->SetGeometry(SHAPES.CUBE);
    Floor.transform.LocalScale({ 20.f,1.f,20.f });
    Floor.AddComponent<BoxCollider>()->SetActive(true);
	Floor.SetName("Floor");
    Light* light2 = Floor.AddComponent<Light>();
    light2->DefaultDirectionLight();
    light2->intensity = 1.0f;

	/*tileMap.DebugMode(scene);*/

    //----------------------------------TestWorld----------------------------------

    // Code generated by GC-Engine Exporter Addon
// Add this code to your scene initialization.
// Make sure a 'Scene& scene' variable is available.

// ----- Barrilet -----
    GameObject& Barrilet = GameObject::Create(scene);
    Barrilet.SetName("Barrilet");
    Barrilet.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
    Barrilet.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
    Barrilet.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
    MeshRenderer* p_Barrilet_renderer = Barrilet.AddComponent<MeshRenderer>();
    p_Barrilet_renderer->SetGeometry(GeometryFactory::LoadGeometry("res/World/Test/Barrilet.obj"));
    // p_Barrilet_renderer->SetAlbedoTexture(pYourTexture);

    // ----- Base -----
    GameObject& Base = GameObject::Create(scene);
    Base.SetName("Base");
    Base.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
    Base.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
    Base.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
    MeshRenderer* p_Base_renderer = Base.AddComponent<MeshRenderer>();
    p_Base_renderer->SetGeometry(GeometryFactory::LoadGeometry("res/World/Test/Base.obj"));
    // p_Base_renderer->SetAlbedoTexture(pYourTexture);

    // ----- Cube -----
    GameObject& Cube = GameObject::Create(scene);
    Cube.SetName("Cube");
    Cube.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
    Cube.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
    Cube.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
    MeshRenderer* p_Cube_renderer = Cube.AddComponent<MeshRenderer>();
    p_Cube_renderer->SetGeometry(GeometryFactory::LoadGeometry("res/World/Test/Cube.obj"));
    // p_Cube_renderer->SetAlbedoTexture(pYourTexture);

    // ----- Base.001 -----
    GameObject& Base_001 = GameObject::Create(scene);
    Base_001.SetName("Base.001");
    Base_001.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
    Base_001.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
    Base_001.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
    MeshRenderer* p_Base_001_renderer = Base_001.AddComponent<MeshRenderer>();
    p_Base_001_renderer->SetGeometry(GeometryFactory::LoadGeometry("res/World/Test/Base.001.obj"));
    // p_Base_001_renderer->SetAlbedoTexture(pYourTexture);

    // ----- Cube.001 -----
    GameObject& Cube_001 = GameObject::Create(scene);
    Cube_001.SetName("Cube.001");
    Cube_001.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
    Cube_001.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
    Cube_001.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
    MeshRenderer* p_Cube_001_renderer = Cube_001.AddComponent<MeshRenderer>();
    p_Cube_001_renderer->SetGeometry(GeometryFactory::LoadGeometry("res/World/Test/Cube.001.obj"));
    // p_Cube_001_renderer->SetAlbedoTexture(pYourTexture);

    // ----- Cylinder -----
    GameObject& Cylinder = GameObject::Create(scene);
    Cylinder.SetName("Cylinder");
    Cylinder.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
    Cylinder.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
    Cylinder.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
    MeshRenderer* p_Cylinder_renderer = Cylinder.AddComponent<MeshRenderer>();
    p_Cylinder_renderer->SetGeometry(GeometryFactory::LoadGeometry("res/World/Test/Cylinder.obj"));
    // p_Cylinder_renderer->SetAlbedoTexture(pYourTexture);

    // ----- Cylinder.001 -----
    GameObject& Cylinder_001 = GameObject::Create(scene);
    Cylinder_001.SetName("Cylinder.001");
    Cylinder_001.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
    Cylinder_001.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
    Cylinder_001.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
    MeshRenderer* p_Cylinder_001_renderer = Cylinder_001.AddComponent<MeshRenderer>();
    p_Cylinder_001_renderer->SetGeometry(GeometryFactory::LoadGeometry("res/World/Test/Cylinder.001.obj"));
    // p_Cylinder_001_renderer->SetAlbedoTexture(pYourTexture);

    // ----- Cube.002 -----
    GameObject& Cube_002 = GameObject::Create(scene);
    Cube_002.SetName("Cube.002");
    Cube_002.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
    Cube_002.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
    Cube_002.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
    MeshRenderer* p_Cube_002_renderer = Cube_002.AddComponent<MeshRenderer>();
    p_Cube_002_renderer->SetGeometry(GeometryFactory::LoadGeometry("res/World/Test/Cube.002.obj"));
    // p_Cube_002_renderer->SetAlbedoTexture(pYourTexture);

    // ----- Cylinder.002 -----
    GameObject& Cylinder_002 = GameObject::Create(scene);
    Cylinder_002.SetName("Cylinder.002");
    Cylinder_002.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
    Cylinder_002.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
    Cylinder_002.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
    MeshRenderer* p_Cylinder_002_renderer = Cylinder_002.AddComponent<MeshRenderer>();
    p_Cylinder_002_renderer->SetGeometry(GeometryFactory::LoadGeometry("res/World/Test/Cylinder.002.obj"));
    // p_Cylinder_002_renderer->SetAlbedoTexture(pYourTexture);

    // ----- Sphere -----
    GameObject& Sphere = GameObject::Create(scene);
    Sphere.SetName("Sphere");
    Sphere.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
    Sphere.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
    Sphere.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
    MeshRenderer* p_Sphere_renderer = Sphere.AddComponent<MeshRenderer>();
    p_Sphere_renderer->SetGeometry(GeometryFactory::LoadGeometry("res/World/Test/Sphere.obj"));
    // p_Sphere_renderer->SetAlbedoTexture(pYourTexture);

    //----------------------------------Run----------------------------------
    testObject.transform.SetWorldPosition({ -2.0f,3.0f,0.0f });
    PlayerObject.transform.SetWorldPosition({ 0.0f,0.f,-10.0f });
    Weapon.transform.SetWorldPosition({ 1.0f,0.0f,-8.0f });
	Weapon.SetName("Weapon_1");

    SnowManObject.transform.SetWorldPosition({ 1.0f,0.0f,1.0f });
    SnowManObject.transform.SetWorldRotation({ 90.0f,0.0f,0.0f });
    SnowMan* Snowman = new SnowMan(&SnowManObject);
    RessourcesManager::AddEntities(Snowman);

    GameObject& SnowManObject2 = GameObject::Create(scene);
    SnowManObject2.transform.SetWorldPosition({ -3.0f, 0.0f, 3.0f });
    SnowManObject2.transform.SetWorldRotation({ 90.0f, 0.0f, 0.0f });
    SnowMan* Snowman2 = new SnowMan(&SnowManObject2);
    RessourcesManager::AddEntities(Snowman2);

    GameObject& SnowManObject3 = GameObject::Create(scene);
    SnowManObject3.transform.SetWorldPosition({ 3.0f, 0.0f, 3.0f });
    SnowManObject3.transform.SetWorldRotation({ 90.0f, 0.0f, 0.0f });
    SnowMan* Snowman3 = new SnowMan(&SnowManObject3);
    RessourcesManager::AddEntities(Snowman3);

    Player* player = new Player(&PlayerObject);
    player->GetGameObject()->AddChild(CameraObject);
    player->GetGameObject()->AddChild(Weapon);
    RessourcesManager::SetPlayer(player);
    RessourcesManager::AddEntities(player);

    MenuManager::Create(&scene);

    gce::GameManager::Run(params);
    gce::GameManager::Destroy();
    gce::Console::UnInit();
    return 0;
}