// Code generated by GC-Engine Exporter Addon
// Add this code to your scene initialization.
// Make sure a 'Scene& scene' variable is available.

// ----- Barrilet -----
GameObject& Barrilet = GameObject::Create(scene);
Barrilet.SetName("Barrilet");
Barrilet.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
Barrilet.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
Barrilet.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
MeshRenderer* p_Barrilet_renderer = Barrilet.AddComponent<MeshRenderer>();
p_Barrilet_renderer->SetGeometry(GeometryFactory::LoadGeometry("Barrilet.obj"));
// p_Barrilet_renderer->SetAlbedoTexture(pYourTexture);

// ----- Base -----
GameObject& Base = GameObject::Create(scene);
Base.SetName("Base");
Base.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
Base.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
Base.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
MeshRenderer* p_Base_renderer = Base.AddComponent<MeshRenderer>();
p_Base_renderer->SetGeometry(GeometryFactory::LoadGeometry("Base.obj"));
// p_Base_renderer->SetAlbedoTexture(pYourTexture);

// ----- Cube -----
GameObject& Cube = GameObject::Create(scene);
Cube.SetName("Cube");
Cube.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
Cube.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
Cube.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
MeshRenderer* p_Cube_renderer = Cube.AddComponent<MeshRenderer>();
p_Cube_renderer->SetGeometry(GeometryFactory::LoadGeometry("Cube.obj"));
// p_Cube_renderer->SetAlbedoTexture(pYourTexture);

// ----- Base.001 -----
GameObject& Base_001 = GameObject::Create(scene);
Base_001.SetName("Base.001");
Base_001.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
Base_001.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
Base_001.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
MeshRenderer* p_Base_001_renderer = Base_001.AddComponent<MeshRenderer>();
p_Base_001_renderer->SetGeometry(GeometryFactory::LoadGeometry("Base.001.obj"));
// p_Base_001_renderer->SetAlbedoTexture(pYourTexture);

// ----- Cube.001 -----
GameObject& Cube_001 = GameObject::Create(scene);
Cube_001.SetName("Cube.001");
Cube_001.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
Cube_001.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
Cube_001.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
MeshRenderer* p_Cube_001_renderer = Cube_001.AddComponent<MeshRenderer>();
p_Cube_001_renderer->SetGeometry(GeometryFactory::LoadGeometry("Cube.001.obj"));
// p_Cube_001_renderer->SetAlbedoTexture(pYourTexture);

// ----- Cylinder -----
GameObject& Cylinder = GameObject::Create(scene);
Cylinder.SetName("Cylinder");
Cylinder.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
Cylinder.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
Cylinder.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
MeshRenderer* p_Cylinder_renderer = Cylinder.AddComponent<MeshRenderer>();
p_Cylinder_renderer->SetGeometry(GeometryFactory::LoadGeometry("Cylinder.obj"));
// p_Cylinder_renderer->SetAlbedoTexture(pYourTexture);

// ----- Cylinder.001 -----
GameObject& Cylinder_001 = GameObject::Create(scene);
Cylinder_001.SetName("Cylinder.001");
Cylinder_001.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
Cylinder_001.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
Cylinder_001.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
MeshRenderer* p_Cylinder_001_renderer = Cylinder_001.AddComponent<MeshRenderer>();
p_Cylinder_001_renderer->SetGeometry(GeometryFactory::LoadGeometry("Cylinder.001.obj"));
// p_Cylinder_001_renderer->SetAlbedoTexture(pYourTexture);

// ----- Cube.002 -----
GameObject& Cube_002 = GameObject::Create(scene);
Cube_002.SetName("Cube.002");
Cube_002.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
Cube_002.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
Cube_002.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
MeshRenderer* p_Cube_002_renderer = Cube_002.AddComponent<MeshRenderer>();
p_Cube_002_renderer->SetGeometry(GeometryFactory::LoadGeometry("Cube.002.obj"));
// p_Cube_002_renderer->SetAlbedoTexture(pYourTexture);

// ----- Cylinder.002 -----
GameObject& Cylinder_002 = GameObject::Create(scene);
Cylinder_002.SetName("Cylinder.002");
Cylinder_002.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
Cylinder_002.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
Cylinder_002.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
MeshRenderer* p_Cylinder_002_renderer = Cylinder_002.AddComponent<MeshRenderer>();
p_Cylinder_002_renderer->SetGeometry(GeometryFactory::LoadGeometry("Cylinder.002.obj"));
// p_Cylinder_002_renderer->SetAlbedoTexture(pYourTexture);

// ----- Sphere -----
GameObject& Sphere = GameObject::Create(scene);
Sphere.SetName("Sphere");
Sphere.transform.SetWorldPosition({ 0.000f, 0.000f, 0.000f });
Sphere.transform.SetWorldRotation({ 0.000f, -0.000f, 0.000f });
Sphere.transform.SetLocalScale({ 1.000f, 1.000f, 1.000f });
MeshRenderer* p_Sphere_renderer = Sphere.AddComponent<MeshRenderer>();
p_Sphere_renderer->SetGeometry(GeometryFactory::LoadGeometry("Sphere.obj"));
// p_Sphere_renderer->SetAlbedoTexture(pYourTexture);